name: CI/CD

on:
  push:
    branches:
      - lab8
  pull_request:
    branches:
      - lab8

jobs:
  ci_cd:
    name: CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - name: Install Flutter GH Pages
        uses: bluefireteam/flutter-gh-pages@v7

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-fatal-warnings --no-fatal-infos lib/templates/lab8/main.dart

      - name: Test project
        run: flutter test

      - name: Build release project
        run: flutter build web --release lib/templates/lab8/main.dart

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web

  build_windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows application
        run: flutter build windows --release

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: ./build/windows
